import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

def generate_load_pwd():
    load_dotenv()
    return os.getenv('POSTGRESQL_PASS')


def generate_engine():
    pwd = generate_load_pwd()
    url_prefix = 'postgresql://factright:'
    url_suffix = '@database-2.ch19a6fwwbwn.us-east-2.rds.amazonaws.com:5432/Dashboard'
    return url_prefix + pwd + url_suffix


def load_projects(data):
    engine = create_engine(generate_engine())
    data.to_sql('Temp SharePoint Projects', engine, if_exists='replace')
    connection = engine.connect()
    upsert = """
INSERT INTO "SharePoint Projects"
    ("index",
    "Id",
    "BaseName",
    "Sponsor",
    "ReportStatus1",
    "SPW",
    "WFProgress",
    "DateInitialStage",
    "DateInProgressRFI",
    "DateInProgressDrafting",
    "DateSponsorReview",
    "DateFinalizeProject",
    "DateCompleted1",
    "ProjectLead.Title",
    "ReportType",
    "LinkToOpportunity.Url",
    "First_x0020_Draft_x003f_",
    "QC",
    "Editor0",
    "DraftSentDate",
    "Final",
    "Sponsor.Label",
    "SPW.Description",
    "SPW.Url")
SELECT
    "index",
    "Id",
    "BaseName",
    "Sponsor",
    "ReportStatus1",
    "SPW",
    "WFProgress",
    "DateInitialStage",
    "DateInProgressRFI",
    "DateInProgressDrafting",
    "DateSponsorReview",
    "DateFinalizeProject",
    "DateCompleted1",
    "ProjectLead.Title",
    "ReportType",
    "LinkToOpportunity.Url",
    "First_x0020_Draft_x003f_",
    "QC",
    "Editor0",
    "DraftSentDate",
    "Final",
    "Sponsor.Label",
    "SPW.Description",
    "SPW.Url"
FROM
    "Temp SharePoint Projects"
ON CONFLICT ("Id") DO UPDATE SET
    "index" = EXCLUDED."index",
    "Id" = EXCLUDED."Id",
    "BaseName" = EXCLUDED."BaseName",
    "Sponsor" = EXCLUDED."Sponsor",
    "ReportStatus1" = EXCLUDED."ReportStatus1",
    "SPW" = EXCLUDED."SPW",
    "WFProgress" = EXCLUDED."WFProgress",
    "DateInitialStage" = EXCLUDED."DateInitialStage",
    "DateInProgressRFI" = EXCLUDED."DateInProgressRFI",
    "DateInProgressDrafting" = EXCLUDED."DateInProgressDrafting",
    "DateSponsorReview" = EXCLUDED."DateSponsorReview",
    "DateFinalizeProject" = EXCLUDED."DateFinalizeProject",
    "DateCompleted1" = EXCLUDED."DateCompleted1",
    "ProjectLead.Title" = EXCLUDED."ProjectLead.Title",
    "ReportType" = EXCLUDED."ReportType",
    "LinkToOpportunity.Url" = EXCLUDED."LinkToOpportunity.Url",
    "First_x0020_Draft_x003f_" = EXCLUDED."First_x0020_Draft_x003f_",
    "QC" = EXCLUDED."QC",
    "Editor0" = EXCLUDED."Editor0",
    "DraftSentDate" = EXCLUDED."DraftSentDate",
    "Final" = EXCLUDED."Final",
    "Sponsor.Label" = EXCLUDED."Sponsor.Label",
    "SPW.Description" = EXCLUDED."SPW.Description",
    "SPW.Url" = EXCLUDED."SPW.Url";
    """
    connection.execute(upsert)
    drop = 'DROP TABLE \"Temp SharePoint Projects\";'
    connection.execute(drop)

def load_tasks(data):
    engine = create_engine(generate_engine())
    data.to_sql('Temp SharePoint Tasks', engine, if_exists='replace')
    connection = engine.connect()
    upsert = """
INSERT INTO "SharePoint Tasks"
    ("index",
    "FileSystemObjectType",
    "Id",
    "ServerRedirectedEmbedUri",
    "ServerRedirectedEmbedUrl",
    "ContentTypeId",
    "Title",
    "Priority",
    "Status",
    "PercentComplete",
    "AssignedToId",
    "AssignedToStringId",
    "Body",
    "StartDate",
    "DueDate",
    "Checkmark",
    "RelatedItems",
    "TaskOutcome",
    "Notes1",
    "Complete",
    "OnsiteAttendeesId",
    "OnsiteAttendeesStringId",
    "OnsiteStartDate",
    "OnsiteEndDate",
    "IsThereAnOnsite",
    "KickOffCallStartDate",
    "KickOffCallEndDate",
    "DraftSentDate",
    "Project_x0020_Name",
    "Clarity_x0020_of_x0020_Thought",
    "Readability",
    "Mechanics",
    "Consistency",
    "Report_x0020_Section_x003a__x002",
    "Report_x0020_Section_x003a__x0020",
    "Report_x0020_Section_x003a__x0021",
    "Report_x0020_Section_x003a__x0022",
    "Report_x0020_Section_x003a__x0023",
    "Report_x0020_Section_x003a__x0024",
    "Created",
    "Modified",
    "DateRetainerReceived",
    "ComplianceAssetId",
    "ID",
    "AuthorId",
    "EditorId",
    "OData__UIVersionString",
    "Attachments",
    "GUID",
    "__metadata.id",
    "__metadata.uri",
    "__metadata.etag",
    "__metadata.type",
    "FirstUniqueAncestorSecurableObject.__deferred.uri",
    "RoleAssignments.__deferred.uri",
    "AttachmentFiles.__deferred.uri",
    "ContentType.__deferred.uri",
    "GetDlpPolicyTip.__deferred.uri",
    "FieldValuesAsHtml.__deferred.uri",
    "FieldValuesAsText.__deferred.uri",
    "FieldValuesForEdit.__deferred.uri",
    "File.__deferred.uri",
    "Folder.__deferred.uri",
    "LikedByInformation.__deferred.uri",
    "ParentList.__deferred.uri",
    "Properties.__deferred.uri",
    "Versions.__deferred.uri",
    "PredecessorsId.__metadata.type",
    "PredecessorsId.results",
    "PreviouslyAssignedToStringId.__metadata.type",
    "PreviouslyAssignedToStringId.results",
    "PreviouslyAssignedToStringId")
SELECT 
    "index",
    "FileSystemObjectType",
    "Id",
    "ServerRedirectedEmbedUri",
    "ServerRedirectedEmbedUrl",
    "ContentTypeId",
    "Title",
    "Priority",
    "Status",
    "PercentComplete",
    "AssignedToId",
    "AssignedToStringId",
    "Body",
    "StartDate",
    "DueDate",
    "Checkmark",
    "RelatedItems",
    "TaskOutcome",
    "Notes1",
    "Complete",
    "OnsiteAttendeesId",
    "OnsiteAttendeesStringId",
    "OnsiteStartDate",
    "OnsiteEndDate",
    "IsThereAnOnsite",
    "KickOffCallStartDate",
    "KickOffCallEndDate",
    "DraftSentDate",
    "Project_x0020_Name",
    "Clarity_x0020_of_x0020_Thought",
    "Readability",
    "Mechanics",
    "Consistency",
    "Report_x0020_Section_x003a__x002",
    "Report_x0020_Section_x003a__x0020",
    "Report_x0020_Section_x003a__x0021",
    "Report_x0020_Section_x003a__x0022",
    "Report_x0020_Section_x003a__x0023",
    "Report_x0020_Section_x003a__x0024",
    "Created",
    "Modified",
    "DateRetainerReceived",
    "ComplianceAssetId",
    "ID",
    "AuthorId",
    "EditorId",
    "OData__UIVersionString",
    "Attachments",
    "GUID",
    "__metadata.id",
    "__metadata.uri",
    "__metadata.etag",
    "__metadata.type",
    "FirstUniqueAncestorSecurableObject.__deferred.uri",
    "RoleAssignments.__deferred.uri",
    "AttachmentFiles.__deferred.uri",
    "ContentType.__deferred.uri",
    "GetDlpPolicyTip.__deferred.uri",
    "FieldValuesAsHtml.__deferred.uri",
    "FieldValuesAsText.__deferred.uri",
    "FieldValuesForEdit.__deferred.uri",
    "File.__deferred.uri",
    "Folder.__deferred.uri",
    "LikedByInformation.__deferred.uri",
    "ParentList.__deferred.uri",
    "Properties.__deferred.uri",
    "Versions.__deferred.uri",
    "PredecessorsId.__metadata.type",
    "PredecessorsId.results",
    "PreviouslyAssignedToStringId.__metadata.type",
    "PreviouslyAssignedToStringId.results",
    "PreviouslyAssignedToStringId"
FROM "Temp SharePoint Tasks"
ON CONFLICT ("Id") DO UPDATE SET
    "index" = EXCLUDED."index",
    "FileSystemObjectType" = EXCLUDED."FileSystemObjectType",
    "Id" = EXCLUDED."Id",
    "ServerRedirectedEmbedUri" = EXCLUDED."ServerRedirectedEmbedUri",
    "ServerRedirectedEmbedUrl" = EXCLUDED."ServerRedirectedEmbedUrl",
    "ContentTypeId" = EXCLUDED."ContentTypeId",
    "Title" = EXCLUDED."Title",
    "Priority" = EXCLUDED."Priority",
    "Status" = EXCLUDED."Status",
    "PercentComplete" = EXCLUDED."PercentComplete",
    "AssignedToId" = EXCLUDED."AssignedToId",
    "AssignedToStringId" = EXCLUDED."AssignedToStringId",
    "Body" = EXCLUDED."Body",
    "StartDate" = EXCLUDED."StartDate",
    "DueDate" = EXCLUDED."DueDate",
    "Checkmark" = EXCLUDED."Checkmark",
    "RelatedItems" = EXCLUDED."RelatedItems",
    "TaskOutcome" = EXCLUDED."TaskOutcome",
    "Notes1" = EXCLUDED."Notes1",
    "Complete" = EXCLUDED."Complete",
    "OnsiteAttendeesId" = EXCLUDED."OnsiteAttendeesId",
    "OnsiteAttendeesStringId" = EXCLUDED."OnsiteAttendeesStringId",
    "OnsiteStartDate" = EXCLUDED."OnsiteStartDate",
    "OnsiteEndDate" = EXCLUDED."OnsiteEndDate",
    "IsThereAnOnsite" = EXCLUDED."IsThereAnOnsite",
    "KickOffCallStartDate" = EXCLUDED."KickOffCallStartDate",
    "KickOffCallEndDate" = EXCLUDED."KickOffCallEndDate",
    "DraftSentDate" = EXCLUDED."DraftSentDate",
    "Project_x0020_Name" = EXCLUDED."Project_x0020_Name",
    "Clarity_x0020_of_x0020_Thought" = EXCLUDED."Clarity_x0020_of_x0020_Thought",
    "Readability" = EXCLUDED."Readability",
    "Mechanics" = EXCLUDED."Mechanics",
    "Consistency" = EXCLUDED."Consistency",
    "Report_x0020_Section_x003a__x002" = EXCLUDED."Report_x0020_Section_x003a__x002",
    "Report_x0020_Section_x003a__x0020" = EXCLUDED."Report_x0020_Section_x003a__x0020",
    "Report_x0020_Section_x003a__x0021" = EXCLUDED."Report_x0020_Section_x003a__x0021",
    "Report_x0020_Section_x003a__x0022" = EXCLUDED."Report_x0020_Section_x003a__x0022",
    "Report_x0020_Section_x003a__x0023" = EXCLUDED."Report_x0020_Section_x003a__x0023",
    "Report_x0020_Section_x003a__x0024" = EXCLUDED."Report_x0020_Section_x003a__x0024",
    "Created" = EXCLUDED."Created",
    "Modified" = EXCLUDED."Modified",
    "DateRetainerReceived" = EXCLUDED."DateRetainerReceived",
    "ComplianceAssetId" = EXCLUDED."ComplianceAssetId",
    "ID" = EXCLUDED."ID",
    "AuthorId" = EXCLUDED."AuthorId",
    "EditorId" = EXCLUDED."EditorId",
    "OData__UIVersionString" = EXCLUDED."OData__UIVersionString",
    "Attachments" = EXCLUDED."Attachments",
    "GUID" = EXCLUDED."GUID",
    "__metadata.id" = EXCLUDED."__metadata.id",
    "__metadata.uri" = EXCLUDED."__metadata.uri",
    "__metadata.etag" = EXCLUDED."__metadata.etag",
    "__metadata.type" = EXCLUDED."__metadata.type",
    "FirstUniqueAncestorSecurableObject.__deferred.uri" = EXCLUDED."FirstUniqueAncestorSecurableObject.__deferred.uri",
    "RoleAssignments.__deferred.uri" = EXCLUDED."RoleAssignments.__deferred.uri",
    "AttachmentFiles.__deferred.uri" = EXCLUDED."AttachmentFiles.__deferred.uri",
    "ContentType.__deferred.uri" = EXCLUDED."ContentType.__deferred.uri",
    "GetDlpPolicyTip.__deferred.uri" = EXCLUDED."GetDlpPolicyTip.__deferred.uri",
    "FieldValuesAsHtml.__deferred.uri" = EXCLUDED."FieldValuesAsHtml.__deferred.uri",
    "FieldValuesAsText.__deferred.uri" = EXCLUDED."FieldValuesAsText.__deferred.uri",
    "FieldValuesForEdit.__deferred.uri" = EXCLUDED."FieldValuesForEdit.__deferred.uri",
    "File.__deferred.uri" = EXCLUDED."File.__deferred.uri",
    "Folder.__deferred.uri" = EXCLUDED."Folder.__deferred.uri",
    "LikedByInformation.__deferred.uri" = EXCLUDED."LikedByInformation.__deferred.uri",
    "ParentList.__deferred.uri" = EXCLUDED."ParentList.__deferred.uri",
    "Properties.__deferred.uri" = EXCLUDED."Properties.__deferred.uri",
    "Versions.__deferred.uri" = EXCLUDED."Versions.__deferred.uri",
    "PredecessorsId.__metadata.type" = EXCLUDED."PredecessorsId.__metadata.type",
    "PredecessorsId.results" = EXCLUDED."PredecessorsId.results",
    "PreviouslyAssignedToStringId.__metadata.type" = EXCLUDED."PreviouslyAssignedToStringId.__metadata.type",
    "PreviouslyAssignedToStringId.results" = EXCLUDED."PreviouslyAssignedToStringId.results",
    "PreviouslyAssignedToStringId" = EXCLUDED."PreviouslyAssignedToStringId";
    """
    connection.execute(upsert)
    drop = 'DROP TABLE \"Temp SharePoint Tasks\";'
    connection.execute(drop)
